# Generated by Django 3.1.7 on 2022-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typequestion',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
