# Generated by Django 3.1.7 on 2022-04-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_typequestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
